### ISSUE TITLE
Show URL in Error for easier debugging

### ISSUE THREAD

**Issue by abmyii** [howie6879/ruia#90]
I think errors would be more useful if they also showed the URL of the parsed page. Example:

> ERROR Spider  <Item: extract `...` error, please check selector or set parameter named `default`>, **https://...**

I hacked a solution together by passing around the `url` parameter, but I can't think of a clean solution ATM. Any ideas? I can also push my changes if you would like to see them (very hacky).

**Comment by abmyii** [comment]
Pushed: https://github.com/abmyii/ruia/tree/error_with_url
A terrible hack, causes errors such as these:
```
ERROR asyncio Exception in callback BaseSelectorEventLoop._sock_write_done(11)(<Future finished result=None>)
handle: <Handle BaseSelectorEventLoop._sock_write_done(11)(<Future finished result=None>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 516, in _sock_write_done
    self.remove_writer(fd)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 346, in remove_writer
    self._ensure_fd_no_transport(fd)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 251, in _ensure_fd_no_transport
    raise RuntimeError(
RuntimeError: File descriptor 11 is used by transport <_SelectorSocketTransport fd=11 read=idle write=<polling, bufsize=0>>
```
No idea why; I haven't looked into it yet (did what I needed).

**Comment by howie6879** [comment]
Good issue, but we should this issue by using a clean solution, we can catch the NothingMatchedError error to solve this issue

I'll fix it soon~

**Comment by abmyii** [comment]
> Good issue, but we should find a clean solution, we can catch the NothingMatchedError error to solve this issue
> 
> I'll fix it soon~

Thanks!

**Comment by howie6879** [comment]
I've fixed this issue, do you think this is a good way to handle it?

**Comment by abmyii** [comment]
Ah, a nice solution! I'll test it now and report back. BTW I am very grateful to you for the incredibly quick resolution.

**Comment by abmyii** [comment]
Works perfectly, thanks!

**Comment by abmyii** [comment]
https://github.com/abmyii/ruia/tree/url_in_field_error
I found that certain errors still don't contain URLs, so I hacked an implementatio. `python_documentation_spider.py` - from:

> ruia.exceptions.NothingMatchedError: Extract `titlez` error, please check selector or set parameter named `default`

To:
> ruia.exceptions.NothingMatchedError: Extract `titlez` error, please check selector or set parameter named `default`**, error url: https://docs.python.org/3/**

**Comment by abmyii** [comment]
Actually I just realised I can do this, so it may not be necessary (though probably better)
```
        try:
            field = await Field.get_item(html=response.html)
        except:
            logging.root.critical(response.url)
			raise
```

**Comment by howie6879** [comment]
I made a limitation. Only when using the Spider class will the URL be added to the error prompt, because the Item class also has the html and html_etree parameters

**Comment by howie6879** [comment]
Spider is the entrance of the crawler. It must manage countless target websites to be crawled, so you need to know which URL is out of order during debugging, but it is not the same to use only the combination of Field and Item to crawl. We have many ways. Achieve the effect you want, such as what you achieved above.

**Comment by abmyii** [comment]
> We have many ways.

What would you say is the best way?
